from .hflip import HFlip
from .cutout import Cutout
from .grayscale import Grayscale
from .saturation import Saturation
from .brightness import Brightness
from .contrast import Contrast
from .zoom import Zoom
from .sample_pairing import SamplePairing
from .autocontrast import AutoContrast